package com.culturacarabobo.sicuc.backend.entities;

import java.time.LocalDate;

import org.springframework.data.annotation.CreatedDate;
import org.springframework.data.jpa.domain.support.AuditingEntityListener;

import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.EntityListeners;
import jakarta.persistence.FetchType;
import jakarta.persistence.GeneratedValue;
import jakarta.persistence.GenerationType;
import jakarta.persistence.Id;
import jakarta.persistence.JoinColumn;
import jakarta.persistence.ManyToOne;
import jakarta.persistence.Table;

/**
 * Represents a "Cultor" (cultural artist/artisan) entity.
 * <p>
 * This is the core entity mapping to the {@code cultors} table in the database.
 * It includes personal information, contact details, location, and artistic
 * specialization.
 * <p>
 * {@link AuditingEntityListener} is used to automatically populate
 * {@code createdAt}.
 */
@Entity
@EntityListeners(AuditingEntityListener.class)
@Table(name = "cultors")
public class Cultor {

    /**
     * The unique identifier (primary key) for the cultor.
     * Auto-incremented by the database.
     */
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private int id;

    /**
     * The cultor's first name(s). Required.
     */
    @Column(length = 50, nullable = false)
    private String firstName;

    /**
     * The cultor's last name(s). Required.
     */
    @Column(length = 50, nullable = false)
    private String lastName;

    /**
     * The cultor's gender (e.g., "M" or "F"). Required.
     */
    @Column(length = 1, nullable = false)
    private String gender;

    /**
     * The cultor's national identification number (e.g., "V-12345678").
     * Required and must be unique.
     */
    @Column(length = 10, nullable = false, unique = true)
    private String idNumber;

    /**
     * The cultor's date of birth. Required.
     * This field is immutable after creation (enforced by CultorService).
     */
    @Column(nullable = false)
    private LocalDate birthDate;

    /**
     * The cultor's primary phone number (e.g., "0412-1234567").
     * Required and must be unique.
     */
    @Column(length = 12, nullable = false, unique = true)
    private String phoneNumber;

    /**
     * The cultor's email address. Optional, but must be unique if provided.
     */
    @Column(length = 150, unique = true)
    private String email;

    /**
     * The cultor's Instagram handle (e.g., "@username"). Optional, but must be
     * unique if provided.
     */
    @Column(length = 30, unique = true)
    private String instagramUser;

    /**
     * The {@link Municipality} where the cultor resides.
     * This is a many-to-one relationship.
     */
    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "municipality_id", nullable = false)
    private Municipality municipality;

    /**
     * The {@link Parish} where the cultor resides.
     * This is a many-to-one relationship.
     */
    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "parish_id", nullable = false)
    private Parish parish;

    /**
     * The cultor's full home address. Required.
     */
    @Column(length = 100, nullable = false)
    private String homeAddress;

    /**
     * The {@link ArtCategory} of the cultor's primary discipline.
     */
    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "art_category_id", nullable = false)
    private ArtCategory artCategory;

    /**
     * The {@link ArtDiscipline} of the cultor.
     */
    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "art_discipline_id", nullable = false)
    private ArtDiscipline artDiscipline;

    /**
     * A free-text field for a custom discipline, only used if the selected
     * {@link ArtDiscipline} is "Otra...".
     */
    @Column(length = 100)
    private String otherDiscipline;

    /**
     * The number of years the cultor has been active in their field. Required.
     */
    @Column(nullable = false)
    private int yearsOfExperience;

    /**
     * The name of any group, collective, or association the cultor belongs to.
     * Optional.
     */
    @Column(length = 100)
    private String groupName;

    /**
     * Description of any disability the cultor has. Optional.
     */
    @Column(length = 100)
    private String disability;

    /**
     * Description of any chronic illness the cultor has. Optional.
     */
    @Column(length = 100)
    private String illness;

    /**
     * Timestamp of when this cultor was first created.
     * Automatically set by {@link AuditingEntityListener} and cannot be updated.
     */
    @CreatedDate
    @Column(nullable = false, updatable = false)
    private LocalDate createdAt;

    /**
     * Default constructor required by JPA.
     */
    public Cultor() {
    }

    /**
     * All-arguments constructor for creating new Cultor instances.
     * (Generated by IDE or written manually).
     */
    public Cultor(String firstName, String lastName, String gender, String idNumber, LocalDate birthDate,
            String phoneNumber, String email, String instagramUser, Municipality municipality, Parish parish,
            String homeAddress, ArtCategory artCategory, ArtDiscipline artDiscipline, String otherDiscipline,
            int yearsOfExperience, String groupName, String disability, String illness) {
        this.firstName = firstName;
        this.lastName = lastName;
        this.gender = gender;
        this.idNumber = idNumber;
        this.birthDate = birthDate;
        this.phoneNumber = phoneNumber;
        this.email = email;
        this.instagramUser = instagramUser;
        this.municipality = municipality;
        this.parish = parish;
        this.homeAddress = homeAddress;
        this.artCategory = artCategory;
        this.artDiscipline = artDiscipline;
        this.otherDiscipline = otherDiscipline;
        this.yearsOfExperience = yearsOfExperience;
        this.groupName = groupName;
        this.disability = disability;
        this.illness = illness;
    }

    // --- Standard Getters and Setters ---

    public int getId() {
        return id;
    }

    public void setId(int id) {
        this.id = id;
    }

    public String getFirstName() {
        return firstName;
    }

    public void setFirstName(String firstName) {
        this.firstName = firstName;
    }

    public String getLastName() {
        return lastName;
    }

    public void setLastName(String lastName) {
        this.lastName = lastName;
    }

    public String getGender() {
        return gender;
    }

    public void setGender(String gender) {
        this.gender = gender;
    }

    public String getIdNumber() {
        return idNumber;
    }

    public void setIdNumber(String idNumber) {
        this.idNumber = idNumber;
    }

    public LocalDate getBirthDate() {
        return birthDate;
    }

    public void setBirthDate(LocalDate birthDate) {
        this.birthDate = birthDate;
    }

    public String getPhoneNumber() {
        return phoneNumber;
    }

    public void setPhoneNumber(String phoneNumber) {
        this.phoneNumber = phoneNumber;
    }

    public String getEmail() {
        return email;
    }

    public void setEmail(String email) {
        this.email = email;
    }

    public String getInstagramUser() {
        return instagramUser;
    }

    public void setInstagramUser(String instagramUser) {
        this.instagramUser = instagramUser;
    }

    public Municipality getMunicipality() {
        return municipality;
    }

    public void setMunicipality(Municipality municipality) {
        this.municipality = municipality;
    }

    public Parish getParish() {
        return parish;
    }

    public void setParish(Parish parish) {
        this.parish = parish;
    }

    public String getHomeAddress() {
        return homeAddress;
    }

    public void setHomeAddress(String homeAddress) {
        this.homeAddress = homeAddress;
    }

    public ArtCategory getArtCategory() {
        return artCategory;
    }

    public void setArtCategory(ArtCategory artCategory) {
        this.artCategory = artCategory;
    }

    public ArtDiscipline getArtDiscipline() {
        return artDiscipline;
    }

    public void setArtDiscipline(ArtDiscipline artDiscipline) {
        this.artDiscipline = artDiscipline;
    }

    public String getOtherDiscipline() {
        return otherDiscipline;
    }

    public void setOtherDiscipline(String otherDiscipline) {
        this.otherDiscipline = otherDiscipline;
    }

    public int getYearsOfExperience() {
        return yearsOfExperience;
    }

    public void setYearsOfExperience(int yearsOfExperience) {
        this.yearsOfExperience = yearsOfExperience;
    }

    public String getGroupName() {
        return groupName;
    }

    public void setGroupName(String groupName) {
        this.groupName = groupName;
    }

    public String getDisability() {
        return disability;
    }

    public void setDisability(String disability) {
        this.disability = disability;
    }

    public String getIllness() {
        return illness;
    }

    public void setIllness(String illness) {
        this.illness = illness;
    }

    public LocalDate getCreatedAt() {
        return createdAt;
    }

    public void setCreatedAt(LocalDate createdAt) {
        this.createdAt = createdAt;
    }
}